auto: true
markdown: rdiscount
pygments: true
paginate: 7
exclude:
  - README.md
  - Rakefile
  - script/*
  - Gemfile*
authors:
  greg:
    name: Greg McKeever
    display_name: Greg
    twitter: gmckeever
    github: gmckeever
  aj:
    name: AJ Solimine
    display_name: AJ
    twitter: ajhit406
    github: ajhit406
  arun:
    name: Arun Thampi
    display_name: Arun
    twitter: iamclovin
  lakshan:
    name: Lakshan Perera
    display_name: Lakshan
    twitter: laktek
  pete:
    name: Pete Kim
    display_name: Pete
    twitter: raingrove
  chris_gaslight:
    name: Chris Nelson
    display_name: Chris Nelson
    twitter: superchris